name: sprocd
description: The Smoothie processing daemon responsible for the forwarding and processing of input files.
version: 1.0.0
repository: https://github.com/tytydraco/sprocd
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: any
dependencies:
  path: ^1.8.2
  stdlog: ^1.0.4
